"""Deterministic extraction of numeric facts into SQLite.

Numbers are parsed from structured sources, never generated by a model.
The agent queries this table and cites the source file; vector search
provides narrative context, not figures.

Two sources:
  - the synthetic HR workbook  -> HR_COMP, dimensioned by function/region
  - SEC quarterly statements   -> PUBLIC_FINANCIAL, dimensioned by statement
"""
from __future__ import annotations

import sqlite3

import pandas as pd

from app import config
from app.ingest_xlsx import fiscal_period
from app.schema import HR_COMP, PUBLIC_FINANCIAL

SCHEMA = """
CREATE TABLE IF NOT EXISTS facts (
    id                INTEGER PRIMARY KEY,
    metric            TEXT NOT NULL,     -- headcount, gross margin, ...
    value             REAL NOT NULL,
    unit              TEXT,              -- people, percent, usd, usd_millions
    fiscal_period     TEXT NOT NULL,     -- FY2025 | Q2 FY2025
    function          TEXT,              -- Engineering, Sales, ...
    region            TEXT,              -- Americas, Europe, ...
    statement         TEXT,              -- source statement, filings only
    source_file       TEXT NOT NULL,
    sensitivity_label TEXT NOT NULL      -- enforced on every query
);
CREATE INDEX IF NOT EXISTS idx_lookup
    ON facts (metric, fiscal_period, function, region);
"""

HR_METRICS = {
    "headcount": "people",
    "attrition_pct": "percent",
    "open_roles": "people",
    "band_min_usd": "usd",
    "band_median_usd": "usd",
    "band_max_usd": "usd",
    "avg_equity_grant_usd": "usd",
    "bonus_target_pct": "percent",
}

# Core statements only. The XBRL "(Details)" sheets restate the same
# figures with different groupings and would duplicate every fact.
CORE_STATEMENTS = ("STATEMENTS OF OPERATIONS", "BALANCE SHEETS",
                   "STATEMENTS OF CASH FLOWS", "COMPREHENSIVE INCOME")


# --- HR workbook ---------------------------------------------------------

def _rows_from_hr() -> list[tuple]:
    path = config.SYNTHETIC_DIR / "hr_headcount_comp.xlsx"
    if not path.exists():
        print(f"  warning: {path.name} missing, skipping HR facts")
        return []

    book = pd.ExcelFile(path)
    rows = []
    for sheet in book.sheet_names:
        df = book.parse(sheet)          # header row is row 0
        for _, record in df.iterrows():
            for metric, unit in HR_METRICS.items():
                if metric not in df.columns or pd.isna(record[metric]):
                    continue
                rows.append((
                    metric,
                    float(record[metric]),
                    unit,
                    str(record["fiscal_period"]),
                    str(record.get("function") or ""),
                    str(record.get("region") or ""),
                    "",                         # statement: n/a for HR
                    path.name,
                    HR_COMP,
                ))
    return rows


# --- SEC quarterly statements -------------------------------------------

def _clean_metric(label) -> str:
    return " ".join(str(label).strip().rstrip(":").split()).lower()


def _is_indented(label) -> bool:
    """SEC statements indent sub-lines under a section header."""
    raw = str(label)
    return raw.startswith((" ", "\xa0", "\t"))


def _period_for(header, duration: str, fallback: str) -> str:
    """Period label that distinguishes a quarter from cumulative figures.

    Columns for the same statement carry both 3-month and 6-month values.
    Conflating them would report half-year revenue as quarterly revenue.
    """
    try:
        stamp = pd.to_datetime(str(header))
    except (ValueError, TypeError):
        return fallback
    period = fiscal_period(stamp.strftime("%Y-%m-%d"))
    return period if duration == "3" else f"{period} (6M cumulative)"


def _rows_from_sheet(df, title: str, path) -> list[tuple]:
    # Row 0 marks 3- vs 6-month column groups; row 1 holds the dates.
    durations, current = [], "3"
    for j in range(df.shape[1]):
        cell = str(df.iloc[0, j])
        if "6 Months" in cell:
            current = "6"
        elif "3 Months" in cell:
            current = "3"
        durations.append(current)

    headers = [df.iloc[1, j] for j in range(df.shape[1])]

    rows = []
    section = ""
    for i in range(2, len(df)):
        label = df.iloc[i, 0]
        if pd.isna(label):
            continue
        metric = _clean_metric(label)
        if not metric:
            continue

        has_values = any(
            isinstance(df.iloc[i, j], (int, float)) and not pd.isna(df.iloc[i, j])
            for j in range(1, df.shape[1])
        )
        if not has_values:
            section = metric          # header row: remember it, emit nothing
            continue

        full_metric = f"{section} - {metric}" if _is_indented(label) and section \
            else metric

        for j in range(1, df.shape[1]):
            value = df.iloc[i, j]
            if pd.isna(value) or not isinstance(value, (int, float)):
                continue
            rows.append((
                full_metric,
                float(value),
                "usd_millions",
                _period_for(headers[j], durations[j], path.stem[-10:]),
                "", "",
                title[:60],
                path.name,
                PUBLIC_FINANCIAL,
            ))
    return rows


def _rows_from_filings() -> list[tuple]:
    rows = []
    for path in sorted(config.RAW_DIR.glob("*.xlsx")):
        book = pd.ExcelFile(path)
        found = 0
        for sheet in book.sheet_names:
            df = book.parse(sheet, header=None)
            if df.shape[0] < 3 or df.shape[1] < 2:
                continue
            title = str(df.iloc[0, 0]).strip()
            if not any(key in title.upper() for key in CORE_STATEMENTS):
                continue
            extracted = _rows_from_sheet(df, title, path)
            rows.extend(extracted)
            found += len(extracted)
        print(f"  {path.name}: {found} facts")
    return rows


# --- Build ---------------------------------------------------------------

def build() -> None:
    config.DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(config.DB_PATH)
    conn.executescript(SCHEMA)
    conn.execute("DELETE FROM facts")    # derived state: rebuild, never patch

    print("HR workbook:")
    hr_rows = _rows_from_hr()
    print(f"  {len(hr_rows)} facts")

    # DISABLED: SEC statement layouts vary across filings. Sub-lines like
    # Products/Services sit under a "Net sales" header, and pandas strips the
    # indentation that would distinguish them — so distinct line items collide
    # under one metric name and aggregates come out wrong (190,718 instead of
    # 95,359). Filing figures go through retrieval, which cites a source the
    # user can verify. Fix would be section-aware label composition.
    print("SEC filings: extraction disabled (see comment)")
    filing_rows = []

    all_rows = hr_rows + filing_rows
    # The same figure appears in multiple filings as prior-year comparatives.
    deduped = list(dict.fromkeys(all_rows))
    print(f"  {len(all_rows) - len(deduped)} duplicate rows removed")

    conn.executemany(
        "INSERT INTO facts (metric, value, unit, fiscal_period, function, "
        "region, statement, source_file, sensitivity_label) "
        "VALUES (?,?,?,?,?,?,?,?,?)",
        deduped,
    )
    conn.commit()

    total = conn.execute("SELECT COUNT(*) FROM facts").fetchone()[0]
    print(f"\nWrote {total} facts to {config.DB_PATH}")

    print("\nBy sensitivity:")
    for label, count in conn.execute(
        "SELECT sensitivity_label, COUNT(*) FROM facts "
        "GROUP BY sensitivity_label ORDER BY 2 DESC"
    ):
        print(f"  {label:<20} {count}")

    print("\nMost common metrics:")
    for metric, count in conn.execute(
        "SELECT metric, COUNT(*) FROM facts GROUP BY metric "
        "ORDER BY 2 DESC LIMIT 12"
    ):
        print(f"  {metric[:45]:<47} {count}")

    
    conn.close()


if __name__ == "__main__":
    build()